// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWLo1YJl8L2kOvVpoisKQxy3y3CuiP_jU',
    appId: '1:991147658626:web:1e17f461059e8d9647939b',
    messagingSenderId: '991147658626',
    projectId: 'jobcdp-d1854',
    authDomain: 'jobcdp-d1854.firebaseapp.com',
    storageBucket: 'jobcdp-d1854.appspot.com',
    measurementId: 'G-0DZPY7ZXYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARkMIjOK6-hT_JhvPmyT7nYVJ1JcY74TQ',
    appId: '1:991147658626:android:a56063c2e2465cf247939b',
    messagingSenderId: '991147658626',
    projectId: 'jobcdp-d1854',
    storageBucket: 'jobcdp-d1854.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnYgNA_PwEH_wjbcJILU65U-OYLpPUUnw',
    appId: '1:991147658626:ios:f45333d42dedadc647939b',
    messagingSenderId: '991147658626',
    projectId: 'jobcdp-d1854',
    storageBucket: 'jobcdp-d1854.appspot.com',
    iosClientId: '991147658626-dd6c3nl214kecjsnmdqiel35n453njqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobcdp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnYgNA_PwEH_wjbcJILU65U-OYLpPUUnw',
    appId: '1:991147658626:ios:f45333d42dedadc647939b',
    messagingSenderId: '991147658626',
    projectId: 'jobcdp-d1854',
    storageBucket: 'jobcdp-d1854.appspot.com',
    iosClientId: '991147658626-dd6c3nl214kecjsnmdqiel35n453njqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobcdp',
  );
}
